apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/common/docker-compose.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: kafkaserver
  name: kafkaserver
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavalible: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafkaserver
    spec:
      containers:
      - image: spotify/kafka
        name: kafkaserver
        ports:
        - containerPort: 2181
        - containerPort: 9092
        resources:
          limits:
            memory: "1073741824"
      restartPolicy: Always
status: {}
