apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/common/docker-compose.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: zuulserver
  name: zuulserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zuulserver
    spec:
      containers:
      - env:
        - name: CONFIGSERVER_URI
          value: http://configserver:8888
        - name: EUREKASERVER_URI
          value: http://eurekaserver:8761/eureka/
        - name: PROFILE
          value: default
        - name: SERVER_PORT
          value: "5555"
        image: motoguard/routingservice:BUILD_NAME
        name: zuulserver
        ports:
        - containerPort: 5555
      restartPolicy: Always
status: {}
