apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/common/docker-compose.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: newsservice
  name: newsservice
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavalible: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: newsservice
    spec:
      containers:
      - env:
        - name: AUTHSERVER_URI
          value: http://authenticationservice:8901/user
        - name: CONFIGSERVER_URI
          value: http://configserver:8888
        - name: DATABASESERVER_URI
          value: http://database:5432
        - name: ENCRYPT_KEY
          value: IMSYMMETRIC
        - name: EUREKASERVER_URI
          value: http://eurekaserver:8761/eureka/
        - name: KAFKASERVER_URI
          value: kafkaserver
        - name: PROFILE
          value: default
        - name: SERVER_PORT
          value: "8085"
        - name: ZKSERVER_URI
          value: kafkaserver
        image: motoguard/newsservice:BUILD_NAME
        name: newsservice
        ports:
        - containerPort: 8085
      restartPolicy: Always
status: {}
