apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: motoguard-ingress
spec:
  rules:
  - http:
    paths:
    - path: /
      backend:
        serviceName: zuulserver
        servicePort: 5555
    - path: /auth
      backend:
        serviceName: authenticationservice
        servicePort: 8901