apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/common/docker-compose.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: licensingservice
  name: licensingservice
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: licensingservice
    spec:
      containers:
      - env:
        - name: AUTHSERVER_URI
          value: http://authenticationservice:8901/user
        - name: CONFIGSERVER_URI
          value: http://configserver:8888
        - name: ENCRYPT_KEY
          value: IMSYMMETRIC
        - name: EUREKASERVER_URI
          value: http://eurekaserver:8761/eureka/
        - name: KAFKASERVER_URI
          value: kafkaserver
        - name: PROFILE
          value: aws-dev
        - name: SERVER_PORT
          value: "8080"
        - name: ZKSERVER_URI
          value: kafkaserver
        image: motoguard/rawdataservice:BUILD_NAME
        name: licensingservice
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1073741824"
      restartPolicy: OnFailure
status: {}
